
# General configs
baseurl: ''
url: ''
lang: pt_BR

# SEO cofigs
head:
  title: Your awesome title
  description: The description
  author: You
  github: username
  codepen: username
  linkedin: username
  themeColor: purple
  imagePathMain: /path/to/img

  jsonld:
    type: person
    name: You name
    url: example@example.com.br
    email: your-email@domain.com

  twitter:
    author: Your username

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - src
